In [19]:
import pandas as pd

In [20]:
accidents_df = pd.read_csv('accidentsFull.csv')
accidents_df.head()

,HOUR_I_R,ALCHL_I,ALIGN_I,STRATUM_R,WRK_ZONE,WKDY_I_R,INT_HWY,LGTCON_I_R,MANCOL_I_R,PED_ACC_R,...,SUR_COND,TRAF_CON_R,TRAF_WAY,VEH_INVL,WEATHER_R,INJURY_CRASH,NO_INJ_I,PRPTYDMG_CRASH,FATALITIES,MAX_SEV_IR
0,0,2,2,1,0,1,0,3,0,0,...,4,0,3,1,1,1,1,0,0,1
1,1,2,1,0,0,1,1,3,2,0,...,4,0,3,2,2,0,0,1,0,0
2,1,2,1,0,0,1,0,3,2,0,...,4,1,2,2,2,0,0,1,0,0
3,1,2,1,1,0,0,0,3,2,0,...,4,1,2,2,1,0,0,1,0,0
4,1,1,1,0,0,1,0,3,2,0,...,4,0,2,3,1,0,0,1,0,0

In [21]:
accidents_df['Injury'] = accidents_df['MAX_SEV_IR'].apply(lambda x: 1 if x in [1, 2] else 0)

In [22]:
df_head = accidents_df.head(12)
df_head.shape
predictors = ['WEATHER_R','TRAF_CON_R']

In [34]:
for predictor in predictors:
    df = df_head[['Injury', predictor]]
    pivot_table = df.pivot_table(df, index='Injury', columns=predictor, aggfunc=len, fill_value=0)
    propTable = pivot_table.apply(lambda x: x /sum(x), axis=1)
    print(propTable)

WEATHER_R         1         2
Injury
0          0.333333  0.666667
1          0.666667  0.333333
TRAF_CON_R         0         1         2
Injury
0           0.666667  0.222222  0.111111
1           1.000000  0.000000  0.000000